// ============================================================
// src/content/grammar/grammarLessons.ts
// Leçons de grammaire avancées — cas, aspects, structure
// ============================================================

import type { Lesson } from '@/types';

export const GRAMMAR_LESSONS: Lesson[] = [

  // ── MODULE 8 : LES CAS POLONAIS ─────────────────────────────

  {
    id: 'lesson_8_1',
    moduleId: 'module_8',
    title: 'Introduction aux 7 cas',
    description: 'Comprendre pourquoi le polonais utilise les cas et comment ils fonctionnent.',
    type: 'grammar',
    difficulty: 'A2',
    order: 1,
    xpReward: 80,
    estimatedMinutes: 6,
    isPremium: true,
    tags: ['cas', 'grammaire', 'bases'],
    exercises: [
      {
        id: 'ex_8_1_1',
        type: 'multiple_choice',
        question: 'Combien de cas y a-t-il en polonais ?',
        correctAnswer: '7',
        options: ['5', '6', '7', '8'],
        explanation: 'Le polonais possède 7 cas : nominatif, génitif, datif, accusatif, instrumental, locatif et vocatif.',
        xpReward: 10,
      },
      {
        id: 'ex_8_1_2',
        type: 'multiple_choice',
        question: 'Quel cas utilise-t-on pour le sujet d\'une phrase ?',
        correctAnswer: 'Le nominatif (Mianownik)',
        options: ['Le génitif (Dopełniacz)', 'Le nominatif (Mianownik)', 'L\'accusatif (Biernik)', 'Le datif (Celownik)'],
        explanation: 'Le nominatif est le cas du sujet. Exemple : "Dom jest duży" — dom est au nominatif.',
        xpReward: 10,
      },
      {
        id: 'ex_8_1_3',
        type: 'multiple_choice',
        question: '"Mieszkam w Warszawie" — pourquoi "Warszawa" devient "Warszawie" ?',
        correctAnswer: 'À cause du locatif après "w"',
        options: [
          'C\'est une erreur',
          'À cause du locatif après "w"',
          'À cause du génitif',
          'À cause de l\'accusatif',
        ],
        explanation: 'Après la préposition "w" (dans), on utilise le locatif. Warszawa → Warszawie au locatif.',
        xpReward: 15,
      },
      {
        id: 'ex_8_1_4',
        type: 'matching',
        question: 'Associez chaque cas à son usage principal',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Nominatif', right: 'Sujet de la phrase' },
          { left: 'Génitif', right: 'Possession, négation' },
          { left: 'Accusatif', right: 'Complément d\'objet direct' },
          { left: 'Instrumental', right: 'Moyen, accompagnement' },
        ],
        xpReward: 20,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'lesson_8_2',
    moduleId: 'module_8',
    title: 'Le Génitif — possession et négation',
    description: 'Maîtrisez le cas le plus fréquent : la possession et la négation.',
    type: 'grammar',
    difficulty: 'A2',
    order: 2,
    xpReward: 80,
    estimatedMinutes: 7,
    isPremium: true,
    tags: ['génitif', 'cas', 'possession', 'négation'],
    exercises: [
      {
        id: 'ex_8_2_1',
        type: 'multiple_choice',
        question: 'Comment dire "la maison de Pierre" en polonais ?',
        correctAnswer: 'dom Piotra (génitif)',
        options: ['dom Piotr', 'dom Piotra (génitif)', 'dom do Piotra', 'dom z Piotra'],
        explanation: 'La possession utilise le génitif : Piotr → Piotra. Pas besoin de "de".',
        xpReward: 10,
      },
      {
        id: 'ex_8_2_2',
        type: 'multiple_choice',
        question: '"Nie ma chleba" signifie...',
        correctAnswer: 'Il n\'y a pas de pain',
        options: ['Je n\'aime pas le pain', 'Il n\'y a pas de pain', 'Je n\'ai pas mangé le pain', 'Le pain n\'est pas bon'],
        explanation: '"Nie ma" + génitif = il n\'y a pas de... "Chleb" → "chleba" au génitif.',
        xpReward: 10,
      },
      {
        id: 'ex_8_2_3',
        type: 'fill_blank',
        question: 'Complétez : "Nie mam ___" (Je n\'ai pas de temps — "czas")',
        correctAnswer: 'czasu',
        options: ['czas', 'czasu', 'czasowi', 'czasem'],
        explanation: 'Après "nie mam" (je n\'ai pas), on utilise le génitif. Czas → czasu.',
        xpReward: 15,
      },
      {
        id: 'ex_8_2_4',
        type: 'translation_fr_pl',
        question: 'Traduisez : "la voiture de ma mère"',
        correctAnswer: 'samochód mojej mamy',
        options: ['samochód moja mama', 'samochód mojej mamy', 'samochód do mojej mamy', 'samochód mojej mamie'],
        explanation: 'Moja mama → mojej mamy au génitif féminin (-a → -i / -y).',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'lesson_8_3',
    moduleId: 'module_8',
    title: 'L\'Accusatif — complément d\'objet',
    description: 'Le cas de l\'objet direct — ce sur quoi porte l\'action.',
    type: 'grammar',
    difficulty: 'A2',
    order: 3,
    xpReward: 80,
    estimatedMinutes: 6,
    isPremium: true,
    tags: ['accusatif', 'cas', 'objet direct'],
    exercises: [
      {
        id: 'ex_8_3_1',
        type: 'multiple_choice',
        question: '"Czytam książkę" — pourquoi "książka" devient "książkę" ?',
        correctAnswer: 'Accusatif — complément d\'objet direct',
        options: [
          'Génitif — après une négation',
          'Accusatif — complément d\'objet direct',
          'Locatif — après une préposition',
          'Instrumental — moyen',
        ],
        explanation: '"Czytam" (je lis) a un objet direct "książkę" (le livre). Au féminin, l\'accusatif : -a → -ę.',
        xpReward: 10,
      },
      {
        id: 'ex_8_3_2',
        type: 'matching',
        question: 'Associez le nominatif à l\'accusatif',
        correctAnswer: 'correct',
        pairs: [
          { left: 'brat (frère)', right: 'brata (accusatif)' },
          { left: 'mama (maman)', right: 'mamę (accusatif)' },
          { left: 'mleko (lait)', right: 'mleko (accusatif)' },
          { left: 'pies (chien)', right: 'psa (accusatif)' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_8_3_3',
        type: 'fill_blank',
        question: 'Complétez : "Kocham ___" (J\'aime maman — mama)',
        correctAnswer: 'mamę',
        options: ['mama', 'mamy', 'mamę', 'mamie'],
        explanation: 'Kochać + accusatif. Mama (féminin) → mamę à l\'accusatif.',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── MODULE 9 : CONJUGAISON ET ASPECTS ────────────────────────

  {
    id: 'lesson_9_1',
    moduleId: 'module_9',
    title: 'Les aspects verbaux — introduction',
    description: 'La différence fondamentale entre perfectif et imperfectif en polonais.',
    type: 'conjugation',
    difficulty: 'A2',
    order: 1,
    xpReward: 100,
    estimatedMinutes: 8,
    isPremium: true,
    tags: ['aspects', 'perfectif', 'imperfectif', 'conjugaison'],
    exercises: [
      {
        id: 'ex_9_1_1',
        type: 'multiple_choice',
        question: '"Czytałem książkę" vs "Przeczytałem książkę" — quelle est la différence ?',
        correctAnswer: 'Le 1er = en train de lire, le 2e = j\'ai fini de lire',
        options: [
          'Aucune différence',
          'Le 1er = en train de lire, le 2e = j\'ai fini de lire',
          'Le 1er = passé, le 2e = présent',
          'Le 1er = singulier, le 2e = pluriel',
        ],
        explanation: 'Czytałem = je lisais (en cours). Przeczytałem = j\'ai lu et terminé le livre (résultat).',
        xpReward: 15,
      },
      {
        id: 'ex_9_1_2',
        type: 'multiple_choice',
        question: 'Pour dire "j\'écris des lettres chaque jour", on utilise...',
        correctAnswer: 'pisać (imperfectif) — action répétée',
        options: [
          'napisać (perfectif)',
          'pisać (imperfectif) — action répétée',
          'Les deux sont corrects',
          'Ni l\'un ni l\'autre',
        ],
        explanation: 'Les actions répétées ou habituelles utilisent l\'imperfectif. "Piszę listy każdego dnia."',
        xpReward: 15,
      },
      {
        id: 'ex_9_1_3',
        type: 'matching',
        question: 'Associez chaque paire aspectuelle',
        correctAnswer: 'correct',
        pairs: [
          { left: 'pisać (imp.)', right: 'napisać (perf.)' },
          { left: 'czytać (imp.)', right: 'przeczytać (perf.)' },
          { left: 'robić (imp.)', right: 'zrobić (perf.)' },
          { left: 'kupować (imp.)', right: 'kupić (perf.)' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_9_1_4',
        type: 'multiple_choice',
        question: 'L\'aspect perfectif peut-il s\'utiliser au présent ?',
        correctAnswer: 'Non — il exprime le futur ou le passé accompli',
        options: [
          'Oui, toujours',
          'Non — il exprime le futur ou le passé accompli',
          'Seulement avec certains verbes',
          'Uniquement à la forme négative',
        ],
        explanation: 'Le perfectif au "présent" exprime en réalité le futur : "napiszę" = j\'écrirai (et terminerai).',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'lesson_9_2',
    moduleId: 'module_9',
    title: 'Être et avoir au présent',
    description: 'Les deux verbes fondamentaux : być (être) et mieć (avoir).',
    type: 'conjugation',
    difficulty: 'A1',
    order: 2,
    xpReward: 60,
    estimatedMinutes: 5,
    isPremium: true,
    tags: ['być', 'mieć', 'conjugaison', 'présent'],
    exercises: [
      {
        id: 'ex_9_2_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "nous sommes" en polonais ?',
        correctAnswer: 'jesteśmy',
        options: ['jesteście', 'jesteśmy', 'są', 'jest'],
        explanation: 'Być (être) : ja jestem, ty jesteś, on/ona jest, my jesteśmy, wy jesteście, oni/one są.',
        xpReward: 10,
      },
      {
        id: 'ex_9_2_2',
        type: 'multiple_choice',
        question: 'Complétez : "Oni ___ w domu."',
        correctAnswer: 'są',
        options: ['jest', 'jesteśmy', 'są', 'jesteście'],
        explanation: '"Oni" (ils) → "są". "One" (elles) → aussi "są".',
        xpReward: 10,
      },
      {
        id: 'ex_9_2_3',
        type: 'matching',
        question: 'Associez chaque pronom à la forme correcte de "mieć"',
        correctAnswer: 'correct',
        pairs: [
          { left: 'ja', right: 'mam' },
          { left: 'ty', right: 'masz' },
          { left: 'on/ona', right: 'ma' },
          { left: 'oni/one', right: 'mają' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_9_2_4',
        type: 'word_order',
        question: 'Formez la phrase : "Tu as un grand appartement"',
        correctAnswer: 'Masz duże mieszkanie',
        words: ['Masz', 'duże', 'mieszkanie'],
        explanation: 'En polonais, l\'ordre est souvent : verbe + adjectif + nom.',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'lesson_9_3',
    moduleId: 'module_9',
    title: 'Les verbes de mouvement',
    description: 'iść vs chodzić, jechać vs jeździć — les paires de déplacement.',
    type: 'conjugation',
    difficulty: 'A2',
    order: 3,
    xpReward: 80,
    estimatedMinutes: 7,
    isPremium: true,
    tags: ['mouvement', 'iść', 'jechać', 'conjugaison'],
    exercises: [
      {
        id: 'ex_9_3_1',
        type: 'multiple_choice',
        question: 'Quelle est la différence entre "iść" et "chodzić" ?',
        correctAnswer: 'iść = une fois maintenant / chodzić = habituellement',
        options: [
          'Aucune différence',
          'iść = une fois maintenant / chodzić = habituellement',
          'iść = à pied / chodzić = en voiture',
          'iść = pluriel / chodzić = singulier',
        ],
        explanation: '"Idę do sklepu" (je vais au magasin maintenant). "Chodzę do sklepu co tydzień" (j\'y vais chaque semaine).',
        xpReward: 15,
      },
      {
        id: 'ex_9_3_2',
        type: 'multiple_choice',
        question: 'Pour dire "je prends le bus pour aller au travail", on utilise...',
        correctAnswer: 'jechać / jeździć (transport)',
        options: [
          'iść / chodzić (à pied)',
          'jechać / jeździć (transport)',
          'latać (voler)',
          'pływać (nager)',
        ],
        explanation: '"Jadę autobusem do pracy." — jechać pour un déplacement en véhicule.',
        xpReward: 10,
      },
      {
        id: 'ex_9_3_3',
        type: 'multiple_choice',
        question: '"Skąd jedziesz?" signifie...',
        correctAnswer: 'D\'où viens-tu (en véhicule) ?',
        options: [
          'Où vas-tu ?',
          'D\'où viens-tu (en véhicule) ?',
          'Comment voyages-tu ?',
          'Pourquoi pars-tu ?',
        ],
        explanation: '"Skąd" = d\'où. "Jedziesz" = tu vas/viens (en véhicule, 2e personne sing. de jechać).',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── MODULE 10 : CULTURE ET EXPRESSIONS ───────────────────────

  {
    id: 'lesson_10_1',
    moduleId: 'module_10',
    title: 'Expressions idiomatiques',
    description: 'Les expressions polonaises intraduisibles qui révèlent la culture.',
    type: 'vocabulary',
    difficulty: 'B1',
    order: 1,
    xpReward: 100,
    estimatedMinutes: 8,
    isPremium: true,
    tags: ['expressions', 'culture', 'idiomes'],
    exercises: [
      {
        id: 'ex_10_1_1',
        type: 'multiple_choice',
        question: '"Nie mój cyrk, nie moje małpy" signifie...',
        correctAnswer: 'Ce n\'est pas mon problème',
        options: [
          'J\'aime le cirque et les singes',
          'Ce n\'est pas mon problème',
          'Je ne travaille pas dans un cirque',
          'Les singes ne sont pas à moi',
        ],
        explanation: 'Littéralement "Ce n\'est pas mon cirque, ce ne sont pas mes singes" = ce n\'est pas mon affaire.',
        xpReward: 15,
      },
      {
        id: 'ex_10_1_2',
        type: 'multiple_choice',
        question: '"Coś jest nie tak" signifie...',
        correctAnswer: 'Quelque chose ne va pas',
        options: [
          'Quelque chose est très bien',
          'Quelque chose ne va pas',
          'Ce n\'est pas comme ça',
          'Il n\'y a rien ici',
        ],
        explanation: '"Coś" = quelque chose, "nie tak" = pas comme ça / pas bien. Expression très courante.',
        xpReward: 10,
      },
      {
        id: 'ex_10_1_3',
        type: 'matching',
        question: 'Associez chaque expression à sa signification',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Sto lat!', right: 'Joyeux anniversaire !' },
          { left: 'Na zdrowie!', right: 'À votre santé ! / À vos souhaits !' },
          { left: 'Smacznego!', right: 'Bon appétit !' },
          { left: 'Powodzenia!', right: 'Bonne chance !' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_10_1_4',
        type: 'multiple_choice',
        question: 'En Pologne, quand quelqu\'un éternue, on dit...',
        correctAnswer: '"Na zdrowie!" (À votre santé !)',
        options: [
          '"Przepraszam" (Pardon)',
          '"Na zdrowie!" (À votre santé !)',
          '"Dobranoc" (Bonne nuit)',
          '"Dziękuję" (Merci)',
        ],
        explanation: '"Na zdrowie" = à ta santé, se dit après un éternuement comme "à vos souhaits" en français.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'lesson_10_2',
    moduleId: 'module_10',
    title: 'La culture polonaise en mots',
    description: 'Découvrez la culture polonaise à travers son vocabulaire unique.',
    type: 'vocabulary',
    difficulty: 'B1',
    order: 2,
    xpReward: 100,
    estimatedMinutes: 7,
    isPremium: true,
    tags: ['culture', 'gastronomie', 'fêtes', 'traditions'],
    exercises: [
      {
        id: 'ex_10_2_1',
        type: 'multiple_choice',
        question: 'Qu\'est-ce que le "barszcz" ?',
        correctAnswer: 'Une soupe de betterave rouge',
        options: [
          'Un type de gâteau',
          'Une soupe de betterave rouge',
          'Un instrument de musique',
          'Une danse traditionnelle',
        ],
        explanation: 'Le barszcz (borsch) est la soupe traditionnelle polonaise à base de betterave. Incontournable à Noël.',
        xpReward: 10,
      },
      {
        id: 'ex_10_2_2',
        type: 'multiple_choice',
        question: '"Wigilia" désigne...',
        correctAnswer: 'La veille de Noël (24 décembre)',
        options: [
          'Pâques en Pologne',
          'La veille de Noël (24 décembre)',
          'Un prénom polonais',
          'Le Nouvel An',
        ],
        explanation: 'Wigilia est la fête centrale du Noël polonais, le 24 décembre. On y mange 12 plats sans viande.',
        xpReward: 10,
      },
      {
        id: 'ex_10_2_3',
        type: 'multiple_choice',
        question: 'Le "żurek" est...',
        correctAnswer: 'Une soupe aigre à base de seigle fermenté',
        options: [
          'Un instrument traditionnel',
          'Une soupe aigre à base de seigle fermenté',
          'Un jeu populaire',
          'Une région de Pologne',
        ],
        explanation: 'Le żurek est une soupe polonaise typique de Pâques, à base de farine de seigle fermentée.',
        xpReward: 10,
      },
      {
        id: 'ex_10_2_4',
        type: 'matching',
        question: 'Associez chaque mot culturel à sa définition',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Pierogi', right: 'Raviolis fourrés polonais' },
          { left: 'Kielbasa', right: 'Saucisse polonaise' },
          { left: 'Mazurek', right: 'Gâteau traditionnel de Pâques' },
          { left: 'Babka', right: 'Gâteau de Pâques en forme de couronne' },
        ],
        xpReward: 20,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
