// ============================================================
// src/content/vocabulary/family.ts
// Vocabulaire du module "La famille" (Module 4) — Source unique
// ============================================================

import type { VocabItem } from '@/types';

export const FAMILY_VOCAB: VocabItem[] = [
  {
    id: 'vocab_fam_01',
    moduleId: 'module_4',
    itemType: 'word',
    order: 1,
    front: 'mama',
    back: 'maman',
    phonetic: '[ˈmama]',
    emoji: '👩',
    examplePl: 'Moja mama jest miła.',
    exampleFr: 'Ma mère est gentille.',
    tags: ['famille'],
    isPremium: false,
  },
  {
    id: 'vocab_fam_02',
    moduleId: 'module_4',
    itemType: 'word',
    order: 2,
    front: 'tata',
    back: 'papa',
    phonetic: '[ˈtata]',
    emoji: '👨',
    examplePl: 'Mój tata pracuje w Warszawie.',
    exampleFr: 'Mon père travaille à Varsovie.',
    tags: ['famille'],
    isPremium: false,
  },
  {
    id: 'vocab_fam_03',
    moduleId: 'module_4',
    itemType: 'word',
    order: 3,
    front: 'brat',
    back: 'frère',
    phonetic: '[brat]',
    emoji: '👦',
    examplePl: 'Mój brat studiuje.',
    exampleFr: 'Mon frère étudie.',
    tags: ['famille'],
    isPremium: false,
  },
  {
    id: 'vocab_fam_04',
    moduleId: 'module_4',
    itemType: 'word',
    order: 4,
    front: 'siostra',
    back: 'sœur',
    phonetic: '[ˈɕɔstra]',
    emoji: '👧',
    examplePl: 'Moja siostra mieszka w Krakowie.',
    exampleFr: 'Ma sœur habite à Cracovie.',
    tags: ['famille'],
    isPremium: false,
  },
  {
    id: 'vocab_fam_05',
    moduleId: 'module_4',
    itemType: 'word',
    order: 5,
    front: 'dziadek',
    back: 'grand-père',
    phonetic: '[ˈdʑadɛk]',
    emoji: '👴',
    examplePl: 'Mój dziadek ma osiemdziesiąt lat.',
    exampleFr: 'Mon grand-père a quatre-vingts ans.',
    tags: ['famille'],
    isPremium: false,
  },
  {
    id: 'vocab_fam_06',
    moduleId: 'module_4',
    itemType: 'word',
    order: 6,
    front: 'babcia',
    back: 'grand-mère',
    phonetic: '[ˈbaptɕa]',
    emoji: '👵',
    examplePl: 'Moja babcia robi świetne pierogi.',
    exampleFr: 'Ma grand-mère fait d\'excellents pierogis.',
    tags: ['famille'],
    isPremium: false,
  },
  {
    id: 'vocab_fam_07',
    moduleId: 'module_4',
    itemType: 'phrase',
    order: 7,
    dependsOnIds: ['vocab_fam_02'],
    front: 'To mój tata.',
    back: "C'est mon père.",
    phonetic: '[tɔ muj ˈtata]',
    emoji: '👨',
    words: ['To', 'mój', 'tata.'],
    examplePl: 'To mój tata, ma na imię Jan.',
    exampleFr: "C'est mon père, il s'appelle Jan.",
    tags: ['famille', 'phrase'],
    isPremium: false,
  },
];
