// ============================================================
// src/content/vocabulary/module2.ts
// Vocabulaire du module "Premier contact" (Module 2) — Source unique
// ============================================================

import type { VocabItem } from '@/types';

export const VOCAB_2_1: VocabItem[] = [
  {
    id: 'v_2_1_01',
    moduleId: 'module_2',
    itemType: 'word',
    order: 1,
    front: 'Dzień dobry',
    back: 'Bonjour',
    phonetic: 'djègn dob-re',
    emoji: '☀️',
    examplePl: 'Dzień dobry, pani Anno.',
    exampleFr: 'Bonjour, Madame Anna.',
    tags: ['salutations', 'formel'],
    isPremium: false,
  },
  {
    id: 'v_2_1_02',
    moduleId: 'module_2',
    itemType: 'word',
    order: 2,
    front: 'Cześć',
    back: 'Salut',
    phonetic: 'tchèchtch',
    emoji: '🙋',
    examplePl: 'Cześć, Kasiu!',
    exampleFr: 'Salut, Kasia !',
    tags: ['salutations', 'informel'],
    isPremium: false,
  },
  {
    id: 'v_2_1_03',
    moduleId: 'module_2',
    itemType: 'word',
    order: 3,
    front: 'Dobry wieczór',
    back: 'Bonsoir',
    phonetic: 'dob-re vyè-tchour',
    emoji: '🌆',
    examplePl: 'Dobry wieczór, panie Piotrze.',
    exampleFr: 'Bonsoir, Monsieur Piotr.',
    tags: ['salutations'],
    isPremium: false,
  },
  {
    id: 'v_2_1_04',
    moduleId: 'module_2',
    itemType: 'word',
    order: 4,
    front: 'Do widzenia',
    back: 'Au revoir',
    phonetic: 'do vi-dzè-gna',
    emoji: '👋',
    examplePl: 'Do widzenia, pani Anno.',
    exampleFr: 'Au revoir, Madame Anna.',
    tags: ['salutations', 'formel'],
    isPremium: false,
  },
  {
    id: 'v_2_1_05',
    moduleId: 'module_2',
    itemType: 'word',
    order: 5,
    dependsOnIds: ['v_2_1_02'],
    front: 'Na razie',
    back: 'À plus tard',
    phonetic: 'na ra-jè',
    emoji: '⏳',
    examplePl: 'Cześć, na razie!',
    exampleFr: 'Salut, à plus tard !',
    tags: ['salutations', 'informel'],
    isPremium: false,
  },
  {
    id: 'v_2_1_06',
    moduleId: 'module_2',
    itemType: 'word',
    order: 6,
    front: 'Do zobaczenia',
    back: 'À bientôt',
    phonetic: 'do zo-ba-tchè-gna',
    emoji: '🔜',
    examplePl: 'Do zobaczenia, Kasiu!',
    exampleFr: 'À bientôt, Kasia !',
    tags: ['salutations'],
    isPremium: false,
  },
  {
    id: 'v_2_1_07',
    moduleId: 'module_2',
    itemType: 'word',
    order: 7,
    front: 'Dobranoc',
    back: 'Bonne nuit',
    phonetic: 'dob-ra-nots',
    emoji: '🌙',
    examplePl: 'Dobranoc, Kasiu!',
    exampleFr: 'Bonne nuit, Kasia !',
    tags: ['salutations'],
    isPremium: false,
  },
];

export const MEETING_VOCAB: VocabItem[] = [
  {
    id: 'vocab_meet_01',
    moduleId: 'module_2',
    itemType: 'word',
    order: 1,
    front: 'jak',
    back: 'comment',
    phonetic: 'yak',
    emoji: '❓',
    examplePl: 'Jak masz na imię?',
    exampleFr: 'Comment t\'appelles-tu ?',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_02',
    moduleId: 'module_2',
    itemType: 'word',
    order: 2,
    dependsOnIds: ['vocab_meet_01'],
    front: 'imię',
    back: 'prénom',
    phonetic: 'i miain',
    emoji: '🏷️',
    examplePl: 'Mam na imię Ania.',
    exampleFr: 'Je m\'appelle Ania.',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_03',
    moduleId: 'module_2',
    itemType: 'word',
    order: 3,
    dependsOnIds: ['vocab_meet_02'],
    front: 'jestem',
    back: 'je suis',
    phonetic: 'yèstèm',
    emoji: '👤',
    examplePl: 'Jestem Julien.',
    exampleFr: 'Je suis Julien.',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_04',
    moduleId: 'module_2',
    itemType: 'word',
    order: 4,
    dependsOnIds: ['vocab_meet_03'],
    front: 'nazywać się',
    back: 's\'appeler',
    phonetic: 'na zé vatch chè',
    emoji: '📛',
    examplePl: 'Nazywam się Kowalski.',
    exampleFr: 'Je m\'appelle Kowalski.',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_05',
    moduleId: 'module_2',
    itemType: 'word',
    order: 5,
    dependsOnIds: ['vocab_meet_04'],
    front: 'pan',
    back: 'monsieur (vouvoiement)',
    phonetic: 'pane',
    emoji: '🤵',
    examplePl: 'Jak się pan nazywa?',
    exampleFr: 'Comment vous appelez-vous, monsieur ?',
    tags: ['présentation', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_06',
    moduleId: 'module_2',
    itemType: 'word',
    order: 6,
    dependsOnIds: ['vocab_meet_05'],
    front: 'pani',
    back: 'madame (vouvoiement)',
    phonetic: 'pa ni',
    emoji: '👩‍💼',
    examplePl: 'Jak się pani nazywa?',
    exampleFr: 'Comment vous appelez-vous, madame ?',
    tags: ['présentation', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_07',
    moduleId: 'module_2',
    itemType: 'word',
    order: 7,
    dependsOnIds: ['vocab_meet_06'],
    front: 'Miło mi',
    back: 'Enchanté(e)',
    phonetic: 'miwo mi',
    emoji: '😊',
    examplePl: 'Miło mi cię poznać!',
    exampleFr: 'Ravi de te rencontrer !',
    tags: ['présentation', 'politesse'],
    isPremium: false,
  },
];
