// ============================================================
// src/content/vocabulary/module2.ts
// Vocabulaire du module "Premier contact" (Module 2) — Source unique
// ============================================================

import type { VocabItem } from '@/types';

export const CONTACT_VOCAB: VocabItem[] = [
  {
    id: 'vocab_cont_01',
    moduleId: 'module_2',
    itemType: 'word',
    order: 1,
    front: 'cześć',
    back: 'salut / coucou (informel)',
    phonetic: 'tchè-chtch',
    emoji: '🙋',
    examplePl: 'Cześć! Jestem Ania.',
    exampleFr: 'Salut ! Je suis Ania.',
    tags: ['salutations', 'informel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_02',
    moduleId: 'module_2',
    itemType: 'word',
    order: 2,
    dependsOnIds: ['vocab_cont_01'],
    front: 'dzień dobry',
    back: 'bonjour (formel)',
    phonetic: 'djègn do-bre',
    emoji: '🤝',
    examplePl: 'Dzień dobry, proszę pana.',
    exampleFr: 'Bonjour, monsieur.',
    tags: ['salutations', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_03',
    moduleId: 'module_2',
    itemType: 'word',
    order: 3,
    dependsOnIds: ['vocab_cont_02'],
    front: 'dobry wieczór',
    back: 'bonsoir',
    phonetic: 'do-bre viè-tchour',
    emoji: '🌆',
    examplePl: 'Dobry wieczór wszystkim.',
    exampleFr: 'Bonsoir à tous.',
    tags: ['salutations'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_04',
    moduleId: 'module_2',
    itemType: 'word',
    order: 4,
    dependsOnIds: ['vocab_cont_03'],
    front: 'do widzenia',
    back: 'au revoir (formel)',
    phonetic: 'do vi-dzè-gnia',
    emoji: '🚪',
    examplePl: 'Do widzenia, do jutra.',
    exampleFr: 'Au revoir, à demain.',
    tags: ['salutations', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_05',
    moduleId: 'module_2',
    itemType: 'word',
    order: 5,
    dependsOnIds: ['vocab_cont_04'],
    front: 'pa',
    back: 'salut / bye (informel)',
    phonetic: 'pa',
    emoji: '✌️',
    examplePl: 'Pa, do zobaczenia!',
    exampleFr: 'Salut, à bientôt !',
    tags: ['salutations', 'informel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_06',
    moduleId: 'module_2',
    itemType: 'word',
    order: 6,
    dependsOnIds: ['vocab_cont_05'],
    front: 'dobranoc',
    back: 'bonne nuit',
    phonetic: 'do-bra-nots',
    emoji: '🌙',
    examplePl: 'Dobranoc, śpij dobrze.',
    exampleFr: 'Bonne nuit, dors bien.',
    tags: ['salutations'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_07',
    moduleId: 'module_2',
    itemType: 'phrase',
    order: 7,
    dependsOnIds: ['vocab_cont_01'],
    front: 'Cześć! Jak się masz?',
    back: 'Salut ! Comment vas-tu ?',
    phonetic: 'tchè-chtch ! yak chiain mach ?',
    emoji: '🙋',
    words: ['Cześć!', 'Jak', 'się', 'masz?'],
    examplePl: 'Cześć! Jak się masz? - Dobrze, dziękuję!',
    exampleFr: 'Salut ! Comment vas-tu ? - Bien, merci !',
    tags: ['salutations', 'phrase'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_08',
    moduleId: 'module_2',
    itemType: 'phrase',
    order: 8,
    dependsOnIds: ['vocab_cont_04'],
    front: 'Do widzenia! Miłego dnia!',
    back: 'Au revoir ! Bonne journée !',
    phonetic: 'do vi-dzè-gnia ! mi-wè-go dnia !',
    emoji: '🚪',
    words: ['Do', 'widzenia!', 'Miłego', 'dnia!'],
    examplePl: 'Do widzenia! Miłego dnia życzę.',
    exampleFr: 'Au revoir ! Je vous souhaite une bonne journée.',
    tags: ['salutations', 'phrase'],
    isPremium: false,
  },
];
