// ============================================================
// src/content/vocabulary/module2.ts
// Vocabulaire du module "Premier contact" (Module 2) — Source unique
// ============================================================

import type { VocabItem } from '@/types';

export const CONTACT_VOCAB: VocabItem[] = [
  {
    id: 'vocab_cont_01',
    moduleId: 'module_2',
    itemType: 'word',
    order: 1,
    front: 'cześć',
    back: 'salut / coucou (informel)',
    phonetic: 'tchè-chtch',
    emoji: '🙋',
    examplePl: 'Cześć! Jestem Ania.',
    exampleFr: 'Salut ! Je suis Ania.',
    tags: ['salutations', 'informel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_02',
    moduleId: 'module_2',
    itemType: 'word',
    order: 2,
    dependsOnIds: ['vocab_cont_01'],
    front: 'dzień dobry',
    back: 'bonjour (formel)',
    phonetic: 'djègn do-bre',
    emoji: '🤝',
    examplePl: 'Dzień dobry, proszę pana.',
    exampleFr: 'Bonjour, monsieur.',
    tags: ['salutations', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_03',
    moduleId: 'module_2',
    itemType: 'word',
    order: 3,
    dependsOnIds: ['vocab_cont_02'],
    front: 'dobry wieczór',
    back: 'bonsoir',
    phonetic: 'do-bre viè-tchour',
    emoji: '🌆',
    examplePl: 'Dobry wieczór wszystkim.',
    exampleFr: 'Bonsoir à tous.',
    tags: ['salutations'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_04',
    moduleId: 'module_2',
    itemType: 'word',
    order: 4,
    dependsOnIds: ['vocab_cont_03'],
    front: 'do widzenia',
    back: 'au revoir (formel)',
    phonetic: 'do vi-dzè-gnia',
    emoji: '🚪',
    examplePl: 'Do widzenia, do jutra.',
    exampleFr: 'Au revoir, à demain.',
    tags: ['salutations', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_05',
    moduleId: 'module_2',
    itemType: 'word',
    order: 5,
    dependsOnIds: ['vocab_cont_04'],
    front: 'pa',
    back: 'salut / bye (informel)',
    phonetic: 'pa',
    emoji: '✌️',
    examplePl: 'Pa, do zobaczenia!',
    exampleFr: 'Salut, à bientôt !',
    tags: ['salutations', 'informel'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_06',
    moduleId: 'module_2',
    itemType: 'word',
    order: 6,
    dependsOnIds: ['vocab_cont_05'],
    front: 'dobranoc',
    back: 'bonne nuit',
    phonetic: 'do-bra-nots',
    emoji: '🌙',
    examplePl: 'Dobranoc, śpij dobrze.',
    exampleFr: 'Bonne nuit, dors bien.',
    tags: ['salutations'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_07',
    moduleId: 'module_2',
    itemType: 'phrase',
    order: 7,
    dependsOnIds: ['vocab_cont_01'],
    front: 'Cześć! Jak się masz?',
    back: 'Salut ! Comment vas-tu ?',
    phonetic: 'tchè-chtch ! yak chiain mach ?',
    emoji: '🙋',
    words: ['Cześć!', 'Jak', 'się', 'masz?'],
    examplePl: 'Cześć! Jak się masz? - Dobrze, dziękuję!',
    exampleFr: 'Salut ! Comment vas-tu ? - Bien, merci !',
    tags: ['salutations', 'phrase'],
    isPremium: false,
  },
  {
    id: 'vocab_cont_08',
    moduleId: 'module_2',
    itemType: 'phrase',
    order: 8,
    dependsOnIds: ['vocab_cont_04'],
    front: 'Do widzenia! Miłego dnia!',
    back: 'Au revoir ! Bonne journée !',
    phonetic: 'do vi-dzè-gnia ! mi-wè-go dnia !',
    emoji: '🚪',
    words: ['Do', 'widzenia!', 'Miłego', 'dnia!'],
    examplePl: 'Do widzenia! Miłego dnia życzę.',
    exampleFr: 'Au revoir ! Je vous souhaite une bonne journée.',
    tags: ['salutations', 'phrase'],
    isPremium: false,
  },
];

export const MEETING_VOCAB: VocabItem[] = [
  {
    id: 'vocab_meet_01',
    moduleId: 'module_2',
    itemType: 'word',
    order: 1,
    front: 'jak',
    back: 'comment',
    phonetic: 'yak',
    emoji: '❓',
    examplePl: 'Jak masz na imię?',
    exampleFr: 'Comment t\'appelles-tu ?',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_02',
    moduleId: 'module_2',
    itemType: 'word',
    order: 2,
    dependsOnIds: ['vocab_meet_01'],
    front: 'imię',
    back: 'prénom',
    phonetic: 'i miain',
    emoji: '🏷️',
    examplePl: 'Mam na imię Ania.',
    exampleFr: 'Je m\'appelle Ania.',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_03',
    moduleId: 'module_2',
    itemType: 'word',
    order: 3,
    dependsOnIds: ['vocab_meet_02'],
    front: 'jestem',
    back: 'je suis',
    phonetic: 'yèstèm',
    emoji: '👤',
    examplePl: 'Jestem Julien.',
    exampleFr: 'Je suis Julien.',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_04',
    moduleId: 'module_2',
    itemType: 'word',
    order: 4,
    dependsOnIds: ['vocab_meet_03'],
    front: 'nazywać się',
    back: 's\'appeler',
    phonetic: 'na zé vatch chè',
    emoji: '📛',
    examplePl: 'Nazywam się Kowalski.',
    exampleFr: 'Je m\'appelle Kowalski.',
    tags: ['présentation'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_05',
    moduleId: 'module_2',
    itemType: 'word',
    order: 5,
    dependsOnIds: ['vocab_meet_04'],
    front: 'pan',
    back: 'monsieur (vouvoiement)',
    phonetic: 'pane',
    emoji: '🤵',
    examplePl: 'Jak się pan nazywa?',
    exampleFr: 'Comment vous appelez-vous, monsieur ?',
    tags: ['présentation', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_06',
    moduleId: 'module_2',
    itemType: 'word',
    order: 6,
    dependsOnIds: ['vocab_meet_05'],
    front: 'pani',
    back: 'madame (vouvoiement)',
    phonetic: 'pa ni',
    emoji: '👩‍💼',
    examplePl: 'Jak się pani nazywa?',
    exampleFr: 'Comment vous appelez-vous, madame ?',
    tags: ['présentation', 'formel'],
    isPremium: false,
  },
  {
    id: 'vocab_meet_07',
    moduleId: 'module_2',
    itemType: 'word',
    order: 7,
    dependsOnIds: ['vocab_meet_06'],
    front: 'Miło mi',
    back: 'Enchanté(e)',
    phonetic: 'miwo mi',
    emoji: '😊',
    examplePl: 'Miło mi cię poznać!',
    exampleFr: 'Ravi de te rencontrer !',
    tags: ['présentation', 'politesse'],
    isPremium: false,
  },
];
