// ============================================================
// src/content/lessons/module4_7.ts
// Modules 4-7 : Famille, Nourriture, Ville & Transport, Temps
// ============================================================

import type { Lesson } from '@/types';

// ── MODULE 4 : LA FAMILLE ────────────────────────────────────
export const MODULE_4_LESSONS: Lesson[] = [
  {
    id: 'lesson_4_1',
    moduleId: 'module_4',
    title: 'Les membres de la famille',
    description: 'Vocabulaire essentiel pour parler de sa famille.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['famille', 'vocabulaire'],
    exercises: [
      {
        id: 'ex_4_1_1',
        type: 'matching',
        question: 'Associez chaque membre de la famille',
        correctAnswer: 'correct',
        pairs: [
          { left: 'mama', right: 'maman' },
          { left: 'tata', right: 'papa' },
          { left: 'brat', right: 'frère' },
          { left: 'siostra', right: 'sœur' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_4_1_2',
        type: 'multiple_choice',
        question: 'Comment dit-on "grand-mère" en polonais ?',
        correctAnswer: 'babcia',
        options: ['dziadek', 'babcia', 'ciocia', 'wujek'],
        explanation: 'babcia = grand-mère, dziadek = grand-père, ciocia = tante, wujek = oncle.',
        xpReward: 10,
      },
      {
        id: 'ex_4_1_3',
        type: 'translation_fr_pl',
        question: 'Traduisez : "J\'ai deux frères"',
        correctAnswer: 'Mam dwóch braci',
        options: ['Mam dwa braty', 'Mam dwóch braci', 'Jestem dwóch braci', 'Mam dwie siostry'],
        explanation: 'Après "mam" (j\'ai), le génitif pluriel : brat → braci. Dwóch = deux (animé masculin).',
        xpReward: 15,
      },
      {
        id: 'ex_4_1_4',
        type: 'word_order',
        question: 'Formez : "Ma sœur habite à Cracovie"',
        correctAnswer: 'Moja siostra mieszka w Krakowie',
        words: ['Moja', 'siostra', 'mieszka', 'w', 'Krakowie'],
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_4_2',
    moduleId: 'module_4',
    title: 'Parler de sa famille',
    description: 'Décrire sa famille : âge, profession, caractère.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 2,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['famille', 'description'],
    exercises: [
      {
        id: 'ex_4_2_1',
        type: 'multiple_choice',
        question: '"Mój mąż jest Polakiem" signifie...',
        correctAnswer: 'Mon mari est polonais',
        options: ['Mon fils est polonais', 'Mon mari est polonais', 'Mon frère est polonais', 'Mon père est polonais'],
        explanation: 'mąż = mari. "Polakiem" est l\'instrumental de "Polak" (Polonais).',
        xpReward: 10,
      },
      {
        id: 'ex_4_2_2',
        type: 'fill_blank',
        question: 'Complétez : "Moja córka ___ pięć lat." (Ma fille a cinq ans)',
        correctAnswer: 'ma',
        options: ['jest', 'ma', 'masz', 'mam'],
        explanation: '"Mieć" (avoir) pour exprimer l\'âge. Ma fille = ona → ma.',
        xpReward: 10,
      },
      {
        id: 'ex_4_2_3',
        type: 'translation_fr_pl',
        question: 'Traduisez : "Mon père est médecin"',
        correctAnswer: 'Mój ojciec jest lekarzem',
        options: ['Mój ojciec jest lekarz', 'Mój ojciec jest lekarzem', 'Mój tata ma lekarz', 'Ojciec jest doktor'],
        explanation: 'Profession → instrumental : lekarz → lekarzem. On dit "jest + instrumental" pour la profession.',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_4_3',
    moduleId: 'module_4',
    title: 'Ma famille et moi',
    description: 'Présenter sa famille dans un contexte réel.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 3,
    xpReward: 60,
    estimatedMinutes: 6,
    isPremium: false,
    tags: ['famille', 'présentation'],
    exercises: [
      {
        id: 'ex_4_3_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "enfant unique" ?',
        correctAnswer: 'jedynak (M) / jedynaczka (F)',
        options: ['jedynak / jedynaczka', 'jeden dziecko', 'singletons', 'brat bez siostry'],
        explanation: 'jedynak = enfant unique (garçon), jedynaczka = enfant unique (fille).',
        xpReward: 10,
      },
      {
        id: 'ex_4_3_2',
        type: 'word_order',
        question: 'Formez : "Mes parents habitent en France"',
        correctAnswer: 'Moi rodzice mieszkają we Francji',
        words: ['Moi', 'rodzice', 'mieszkają', 'we', 'Francji'],
        explanation: 'rodzice = parents (pluriel de rodzic). we + locatif = Francja → Francji.',
        xpReward: 20,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ── MODULE 5 : NOURRITURE & BOISSONS ────────────────────────
export const MODULE_5_LESSONS: Lesson[] = [
  {
    id: 'lesson_5_1',
    moduleId: 'module_5',
    title: 'La cuisine polonaise',
    description: 'Découvrez les plats traditionnels et le vocabulaire de la restauration.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['nourriture', 'restaurant', 'culture'],
    exercises: [
      {
        id: 'ex_5_1_1',
        type: 'matching',
        question: 'Associez chaque plat à sa description',
        correctAnswer: 'correct',
        pairs: [
          { left: 'pierogi', right: 'Raviolis fourrés' },
          { left: 'bigos', right: 'Ragoût de choucroute' },
          { left: 'żurek', right: 'Soupe aigre au seigle' },
          { left: 'barszcz', right: 'Soupe de betterave' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_5_1_2',
        type: 'multiple_choice',
        question: 'Que signifie "smacznego" ?',
        correctAnswer: 'Bon appétit',
        options: ['Merci pour le repas', 'Bon appétit', 'C\'est délicieux', 'J\'ai faim'],
        explanation: '"Smacznego !" est l\'expression polonaise pour "bon appétit". Très utilisée !',
        xpReward: 10,
      },
      {
        id: 'ex_5_1_3',
        type: 'translation_fr_pl',
        question: 'Traduisez : "Je voudrais les pierogis"',
        correctAnswer: 'Poproszę pierogi',
        options: ['Chcę pierogi proszę', 'Poproszę pierogi', 'Mam pierogi', 'Lubię pierogi'],
        explanation: '"Poproszę" = je voudrais / s\'il vous plaît (très poli pour commander).',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_5_2',
    moduleId: 'module_5',
    title: 'Commander au restaurant',
    description: 'Savoir commander, demander le prix, payer l\'addition.',
    type: 'dialogue',
    difficulty: 'A1',
    order: 2,
    xpReward: 60,
    estimatedMinutes: 6,
    isPremium: false,
    tags: ['restaurant', 'commande', 'dialogue'],
    exercises: [
      {
        id: 'ex_5_2_1',
        type: 'multiple_choice',
        question: 'Comment demander la carte au restaurant ?',
        correctAnswer: 'Poproszę kartę / menu',
        options: ['Poproszę rachunek', 'Poproszę kartę / menu', 'Co polecacie?', 'Ile kosztuje?'],
        explanation: 'kartę / menu = la carte. "Poproszę" est la formule polie pour commander.',
        xpReward: 10,
      },
      {
        id: 'ex_5_2_2',
        type: 'word_order',
        question: 'Formez : "L\'addition s\'il vous plaît"',
        correctAnswer: 'Poproszę rachunek',
        words: ['Poproszę', 'rachunek'],
        explanation: 'rachunek = facture / addition. Très simple en polonais !',
        xpReward: 10,
      },
      {
        id: 'ex_5_2_3',
        type: 'fill_blank',
        question: 'Complétez : "___ to kosztuje?" (Combien ça coûte ?)',
        correctAnswer: 'Ile',
        options: ['Co', 'Ile', 'Jak', 'Gdzie'],
        explanation: '"Ile" = combien. "Ile to kosztuje?" est la question de base pour le prix.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_5_3',
    moduleId: 'module_5',
    title: 'Les courses et le marché',
    description: 'Acheter des aliments, exprimer les quantités.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 3,
    xpReward: 60,
    estimatedMinutes: 6,
    isPremium: false,
    tags: ['courses', 'quantités', 'marché'],
    exercises: [
      {
        id: 'ex_5_3_1',
        type: 'multiple_choice',
        question: '"Pół kilograma pomidorów" signifie...',
        correctAnswer: 'Un demi-kilo de tomates',
        options: ['Un kilo de tomates', 'Un demi-kilo de tomates', 'Deux kilos de tomates', 'Des tomates s\'il vous plaît'],
        explanation: 'pół = demi, kilogram → kilogram/kilograma (génitif). pomidorów = génitif pluriel de pomidor.',
        xpReward: 15,
      },
      {
        id: 'ex_5_3_2',
        type: 'matching',
        question: 'Associez chaque aliment',
        correctAnswer: 'correct',
        pairs: [
          { left: 'chleb', right: 'pain' },
          { left: 'mleko', right: 'lait' },
          { left: 'jajka', right: 'œufs' },
          { left: 'masło', right: 'beurre' },
        ],
        xpReward: 20,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ── MODULE 6 : VILLE & TRANSPORT ─────────────────────────────
export const MODULE_6_LESSONS: Lesson[] = [
  {
    id: 'lesson_6_1',
    moduleId: 'module_6',
    title: 'Se repérer en ville',
    description: 'Demander et donner des directions.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 1,
    xpReward: 70,
    estimatedMinutes: 6,
    isPremium: true,
    tags: ['ville', 'directions', 'orientation'],
    exercises: [
      {
        id: 'ex_6_1_1',
        type: 'matching',
        question: 'Associez les directions',
        correctAnswer: 'correct',
        pairs: [
          { left: 'prosto', right: 'tout droit' },
          { left: 'w prawo', right: 'à droite' },
          { left: 'w lewo', right: 'à gauche' },
          { left: 'za rogiem', right: 'au coin' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_6_1_2',
        type: 'multiple_choice',
        question: 'Comment dire "Où est la gare ?" en polonais ?',
        correctAnswer: 'Gdzie jest dworzec?',
        options: ['Co jest dworzec?', 'Gdzie jest dworzec?', 'Jak jest dworzec?', 'Kiedy jest dworzec?'],
        explanation: '"Gdzie" = où. "Dworzec" = gare (ferroviaire). "Gdzie jest...?" = Où est... ?',
        xpReward: 10,
      },
      {
        id: 'ex_6_1_3',
        type: 'fill_blank',
        question: 'Complétez : "Proszę jechać ___" (Veuillez aller tout droit)',
        correctAnswer: 'prosto',
        options: ['prawo', 'lewo', 'prosto', 'cofnąć'],
        xpReward: 10,
      },
      {
        id: 'ex_6_1_4',
        type: 'word_order',
        question: 'Formez : "Excusez-moi, où est le centre-ville ?"',
        correctAnswer: 'Przepraszam gdzie jest centrum',
        words: ['Przepraszam', 'gdzie', 'jest', 'centrum'],
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_6_2',
    moduleId: 'module_6',
    title: 'Les transports en commun',
    description: 'Bus, tram, métro — se déplacer dans une ville polonaise.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 2,
    xpReward: 70,
    estimatedMinutes: 6,
    isPremium: true,
    tags: ['transport', 'bus', 'train', 'ville'],
    exercises: [
      {
        id: 'ex_6_2_1',
        type: 'matching',
        question: 'Associez chaque moyen de transport',
        correctAnswer: 'correct',
        pairs: [
          { left: 'autobus', right: 'bus' },
          { left: 'tramwaj', right: 'tramway' },
          { left: 'metro', right: 'métro' },
          { left: 'taksówka', right: 'taxi' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_6_2_2',
        type: 'multiple_choice',
        question: '"Jadę autobusem" — quel cas utilise-t-on ?',
        correctAnswer: 'L\'instrumental — moyen de transport',
        options: ['Le nominatif', 'Le génitif', 'L\'instrumental — moyen de transport', 'L\'accusatif'],
        explanation: 'Pour exprimer le moyen de déplacement, on utilise l\'instrumental. autobus → autobusem.',
        xpReward: 15,
      },
      {
        id: 'ex_6_2_3',
        type: 'translation_fr_pl',
        question: 'Traduisez : "Le train part à 10 heures"',
        correctAnswer: 'Pociąg odjeżdża o dziesiątej',
        options: ['Pociąg jest o 10', 'Pociąg odjeżdża o dziesiątej', 'Autobus o 10', 'Pociąg przyjeżdża o dziesiątej'],
        explanation: 'odjeżdżać = partir (transport). "o dziesiątej" = à dix heures (locatif).',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ── MODULE 7 : TEMPS & DATES ─────────────────────────────────
export const MODULE_7_LESSONS: Lesson[] = [
  {
    id: 'lesson_7_1',
    moduleId: 'module_7',
    title: 'L\'heure en polonais',
    description: 'Dire et demander l\'heure.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 1,
    xpReward: 70,
    estimatedMinutes: 6,
    isPremium: true,
    tags: ['heure', 'temps', 'nombres'],
    exercises: [
      {
        id: 'ex_7_1_1',
        type: 'multiple_choice',
        question: 'Comment demande-t-on l\'heure en polonais ?',
        correctAnswer: 'Która godzina?',
        options: ['Ile jest czasu?', 'Która godzina?', 'Co jest godzina?', 'Jak jest czas?'],
        explanation: '"Która godzina?" = Quelle heure est-il ? "Która" = quelle (féminin).',
        xpReward: 10,
      },
      {
        id: 'ex_7_1_2',
        type: 'matching',
        question: 'Associez les expressions de temps',
        correctAnswer: 'correct',
        pairs: [
          { left: 'rano', right: 'matin' },
          { left: 'południe', right: 'midi' },
          { left: 'wieczór', right: 'soir' },
          { left: 'noc', right: 'nuit' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_7_1_3',
        type: 'multiple_choice',
        question: '"Jest wpół do trzeciej" signifie...',
        correctAnswer: '2h30 (à moitié vers 3h)',
        options: ['3h30', '2h30 (à moitié vers 3h)', '2h45', '3h15'],
        explanation: '"Wpół do" = "à moitié vers" → wpół do trzeciej = 2h30. Système unique en polonais !',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_7_2',
    moduleId: 'module_7',
    title: 'Les jours et les semaines',
    description: 'Les jours de la semaine et les expressions temporelles.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 2,
    xpReward: 70,
    estimatedMinutes: 5,
    isPremium: true,
    tags: ['jours', 'semaine', 'calendrier'],
    exercises: [
      {
        id: 'ex_7_2_1',
        type: 'word_order',
        question: 'Remettez les jours dans l\'ordre (lundi → dimanche)',
        correctAnswer: 'poniedziałek wtorek środa czwartek piątek sobota niedziela',
        words: ['środa', 'piątek', 'wtorek', 'niedziela', 'poniedziałek', 'sobota', 'czwartek'],
        xpReward: 20,
      },
      {
        id: 'ex_7_2_2',
        type: 'multiple_choice',
        question: '"W piątek" signifie...',
        correctAnswer: 'Vendredi (ce vendredi)',
        options: ['Le week-end', 'Vendredi (ce vendredi)', 'Le soir', 'La semaine prochaine'],
        explanation: '"W" + jour de la semaine = "le..." (locatif). W poniedziałek = lundi, etc.',
        xpReward: 10,
      },
      {
        id: 'ex_7_2_3',
        type: 'matching',
        question: 'Associez les expressions temporelles',
        correctAnswer: 'correct',
        pairs: [
          { left: 'dzisiaj', right: 'aujourd\'hui' },
          { left: 'jutro', right: 'demain' },
          { left: 'wczoraj', right: 'hier' },
          { left: 'pojutrze', right: 'après-demain' },
        ],
        xpReward: 20,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_7_3',
    moduleId: 'module_7',
    title: 'Les mois et les saisons',
    description: 'Les mois de l\'année et les quatre saisons.',
    type: 'vocabulary',
    difficulty: 'A2',
    order: 3,
    xpReward: 60,
    estimatedMinutes: 5,
    isPremium: true,
    tags: ['mois', 'saisons', 'calendrier'],
    exercises: [
      {
        id: 'ex_7_3_1',
        type: 'matching',
        question: 'Associez les saisons',
        correctAnswer: 'correct',
        pairs: [
          { left: 'wiosna', right: 'printemps' },
          { left: 'lato', right: 'été' },
          { left: 'jesień', right: 'automne' },
          { left: 'zima', right: 'hiver' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_7_3_2',
        type: 'fill_blank',
        question: 'Complétez : "Urodziłem się ___ maju." (Je suis né en mai)',
        correctAnswer: 'w',
        options: ['na', 'w', 'za', 'do'],
        explanation: '"w" + locatif = en (pour les mois). "w maju" = en mai.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ── Export consolidé ─────────────────────────────────────────
export const ALL_LESSONS = [
  ...MODULE_4_LESSONS,
  ...MODULE_5_LESSONS,
  ...MODULE_6_LESSONS,
  ...MODULE_7_LESSONS,
];
