// ============================================================
// src/content/lessons/module1.ts
// Module 1 — Alphabet & Prononciation (5 leçons)
// ============================================================

import type { Lesson, Exercise } from '@/types';

export const MODULE_1_LESSONS: Lesson[] = [
  {
    id: 'lesson_1_1',
    moduleId: 'module_1',
    title: "L'alphabet polonais",
    description: 'Découvrez les 32 lettres de l\'alphabet polonais et leurs particularités.',
    type: 'pronunciation',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 4,
    isPremium: false,
    tags: ['alphabet', 'prononciation', 'bases'],
    exercises: [
      {
        id: 'ex_1_1_1',
        type: 'multiple_choice',
        question: 'Comment se prononce la lettre "ą" en polonais ?',
        correctAnswer: 'Comme "on" français nasal',
        options: ['Comme "a" simple', 'Comme "on" français nasal', 'Comme "an" aigu', 'Comme "ou"'],
        hint: 'Pensez au son nasal du français !',
        explanation: 'Le "ą" est une voyelle nasale qui se prononce comme le "on" en français, mais plus fermé.',
        xpReward: 10,
      },
      {
        id: 'ex_1_1_2',
        type: 'multiple_choice',
        question: 'La lettre "ł" se prononce comme...',
        correctAnswer: 'Le "w" anglais',
        options: ['Le "l" français', 'Le "w" anglais', 'Le "r" roulé', 'Le "ou" court'],
        explanation: '"Ł" se prononce comme le "w" anglais dans "water". C\'est une particularité du polonais moderne.',
        xpReward: 10,
      },
      {
        id: 'ex_1_1_3',
        type: 'multiple_choice',
        question: 'Comment prononcer "sz" en polonais ?',
        correctAnswer: 'Comme "ch" en français',
        options: ['Comme "s" simple', 'Comme "z"', 'Comme "ch" en français', 'Comme "ks"'],
        explanation: '"Sz" est un digramme qui se prononce comme le "ch" français dans "chat".',
        xpReward: 10,
      },
      {
        id: 'ex_1_1_4',
        type: 'matching',
        question: 'Associez chaque lettre à sa prononciation',
        correctAnswer: 'correct',
        pairs: [
          { left: 'ę', right: 'é nasal' },
          { left: 'ó', right: 'comme "ou"' },
          { left: 'ź', right: 'z doux' },
          { left: 'ż', right: 'z dur (comme j)' },
        ],
        xpReward: 20,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_1_2',
    moduleId: 'module_1',
    title: 'Les consonnes spéciales',
    description: 'Maîtrisez cz, dz, dź, dż et les autres consonnes complexes.',
    type: 'pronunciation',
    difficulty: 'A1',
    order: 2,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['consonnes', 'prononciation'],
    exercises: [
      {
        id: 'ex_1_2_1',
        type: 'multiple_choice',
        question: '"Cz" se prononce comme...',
        correctAnswer: 'Tch (comme dans "tchèque")',
        options: ['Ts', 'Tch (comme dans "tchèque")', 'Ch français', 'Ks'],
        explanation: '"Cz" est l\'équivalent du "tch" français, comme dans "tchat".',
        xpReward: 10,
      },
      {
        id: 'ex_1_2_2',
        type: 'multiple_choice',
        question: 'Comment prononce-t-on "Warszawa" ?',
        correctAnswer: 'Var-CHA-va',
        options: ['War-saw-a', 'Var-CHA-va', 'Var-za-va', 'War-sha-wa'],
        explanation: '"W" = V, "sz" = ch, "w" = v. Donc : Var-CHA-va !',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_1_3',
    moduleId: 'module_1',
    title: 'Accent et rythme',
    description: 'En polonais, l\'accent tombe presque toujours sur l\'avant-dernière syllabe.',
    type: 'pronunciation',
    difficulty: 'A1',
    order: 3,
    xpReward: 50,
    estimatedMinutes: 3,
    isPremium: false,
    tags: ['accent', 'rythme', 'prononciation'],
    exercises: [
      {
        id: 'ex_1_3_1',
        type: 'multiple_choice',
        question: 'Sur quelle syllabe tombe l\'accent en polonais ?',
        correctAnswer: "L'avant-dernière",
        options: ["La première", "La dernière", "L'avant-dernière", "Variable"],
        explanation: 'Presque toujours sur l\'avant-dernière syllabe. Ex : "mu-ZY-ka", "ję-ZYK".',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
