// ============================================================
// src/content/lessons/module2.ts
// Module 2 — Salutations essentielles (4 leçons)
// ============================================================

import type { Lesson } from '@/types';
import { VOCAB_2_1, MEETING_VOCAB } from '@/content/vocabulary/module2';

export const MODULE_2_LESSONS: Lesson[] = [
  {
    id: 'lesson_2_1',
    moduleId: 'module_2',
    title: 'Saluer',
    description: 'Dire bonjour et au revoir. Dzień dobry est poli et valable toute la journée. Cześć est familier et sert aussi à dire au revoir.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 3,
    isPremium: false,
    tags: ['salutations', 'bases', 'premier_contact'],
    discoveryItems: VOCAB_2_1,
    exercises: [
      {
        id: 'ex_2_1_01',
        type: 'multiple_choice',
        question: 'Que veut dire « Dobranoc » ?',
        correctAnswer: 'Bonne nuit',
        options: ['Bonjour', 'Bonne nuit', 'Bonsoir'],
        explanation: 'Dobranoc = Bonne nuit. On le dit le soir, avant de se coucher.',
        xpReward: 10,
      },
      {
        id: 'ex_2_1_02',
        type: 'matching',
        question: 'Associe chaque mot polonais à sa traduction.',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Dzień dobry', right: 'Bonjour' },
          { left: 'Cześć', right: 'Salut' },
          { left: 'Do widzenia', right: 'Au revoir' },
          { left: 'Dobranoc', right: 'Bonne nuit' },
        ],
        explanation: 'Dzień dobry est poli (toute la journée). Cześć est familier (amis, famille).',
        xpReward: 15,
      },
      {
        id: 'ex_2_1_03',
        type: 'fill_blank',
        question: 'Complète : ___, Kasiu! (« Salut, Kasia ! »)',
        correctAnswer: 'Cześć',
        options: ['widzenia', 'razie', 'Cześć'],
        explanation: 'Cześć = Salut. Familier : avec des amis ou la famille.',
        xpReward: 10,
      },
      {
        id: 'ex_2_1_04',
        type: 'word_order',
        question: 'Remets dans l\'ordre : « Bonsoir, Monsieur Piotr. »',
        correctAnswer: 'Dobry wieczór, panie Piotrze.',
        words: ['Dobry', 'wieczór,', 'panie', 'Piotrze.'],
        explanation: 'Dobry wieczór = Bonsoir ; « panie Piotrze » = Monsieur Piotr.',
        xpReward: 15,
      },
      {
        id: 'ex_2_1_05',
        type: 'multiple_choice',
        question: 'Comment dit-on « Bonjour » ?',
        correctAnswer: 'Dzień dobry',
        options: ['Dzień dobry', 'Dobry wieczór', 'Na razie'],
        explanation: 'Dzień dobry = Bonjour. Poli et valable toute la journée.',
        xpReward: 10,
      },
      {
        id: 'ex_2_1_06',
        type: 'matching',
        question: 'Associe chaque mot polonais à sa traduction.',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Dobry wieczór', right: 'Bonsoir' },
          { left: 'Do widzenia', right: 'Au revoir' },
          { left: 'Na razie', right: 'À plus tard' },
          { left: 'Do zobaczenia', right: 'À bientôt' },
        ],
        explanation: 'Na razie = À plus tard (familier). Do zobaczenia = À bientôt.',
        xpReward: 15,
      },
      {
        id: 'ex_2_1_07',
        type: 'word_order',
        question: 'Écoute la phrase puis remets les mots dans l\'ordre.',
        correctAnswer: 'Dzień dobry, pani Anno.',
        words: ['Dzień', 'dobry,', 'pani', 'Anno.'],
        isAudioPrompt: true,
        audioText: 'Dzień dobry, pani Anno.',
        audioKey: 'v_2_1_01_example',
        explanation: 'Dzień dobry, pani Anno. = Bonjour, Madame Anna.',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_2_2',
    moduleId: 'module_2',
    title: 'Faisons connaissance !',
    description: 'Présentations, prénom, nom et formules d\'accueil.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 2,
    xpReward: 50,
    estimatedMinutes: 3,
    isPremium: false,
    tags: ['présentation', 'bases', 'premier_contact'],
    discoveryItems: MEETING_VOCAB,
    exercises: [
      {
        id: 'ex_2_2_1',
        type: 'multiple_choice',
        question: 'Comment demande-t-on le prénom de quelqu\'un ?',
        correctAnswer: 'Jak masz na imię?',
        options: ['Jak masz na imię?', 'Miło mi', 'Nazywam się Kowalski', 'Jestem Julien'],
        explanation: '"Jak masz na imię ?" = Comment t\'appelles-tu ?',
        xpReward: 10,
      },
      {
        id: 'ex_2_2_2',
        type: 'matching',
        question: 'Associez chaque mot à sa traduction',
        correctAnswer: 'correct',
        pairs: [
          { left: 'jak', right: 'comment' },
          { left: 'imię', right: 'prénom' },
          { left: 'pani', right: 'madame' },
        ],
        xpReward: 15,
      },
      {
        id: 'ex_2_2_3',
        type: 'word_order',
        question: 'Écoutez et reconstituez la phrase :',
        correctAnswer: 'Jestem Julien.',
        words: ['Jestem', 'Julien.'],
        isAudioPrompt: true,
        audioText: 'Jestem Julien.',
        xpReward: 15,
      },
      {
        id: 'ex_2_2_4',
        type: 'multiple_choice',
        question: 'Quel mot utilise-t-on pour se présenter formellement (nom) ?',
        correctAnswer: 'nazywać się',
        options: ['nazywać się', 'imię', 'pan', 'pani'],
        explanation: 'nazywać się = s\'appeler (s\'utilise surtout pour le nom de famille).',
        xpReward: 10,
      },
      {
        id: 'ex_2_2_5',
        type: 'matching',
        question: 'Associez chaque emoji au mot correspondant',
        correctAnswer: 'correct',
        pairs: [
          { left: '🤵', right: 'pan' },
          { left: '👩‍💼', right: 'pani' },
          { left: '😊', right: 'Miło mi' },
        ],
        xpReward: 15,
      },
      {
        id: 'ex_2_2_6',
        type: 'fill_blank',
        question: 'Complétez : "___ mi cię poznać!" (Ravi de te rencontrer !)',
        correctAnswer: 'Miło',
        options: ['Miło', 'Jestem', 'Jak', 'Pan'],
        explanation: 'Miło mi = Enchanté(e) / Ravi(e).',
        xpReward: 10,
      },
      {
        id: 'ex_2_2_7',
        type: 'word_order',
        question: 'Reconstituez la phrase : "Je m\'appelle Kowalski."',
        correctAnswer: 'Nazywam się Kowalski.',
        words: ['Nazywam', 'się', 'Kowalski.'],
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_2_3',
    moduleId: 'module_2',
    title: 'Se présenter',
    description: 'Dire son prénom, demander comment s\'appelle quelqu\'un.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 3,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['présentations', 'identité'],
    exercises: [
      {
        id: 'ex_2_3_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "Je m\'appelle Marie" en polonais ?',
        correctAnswer: 'Nazywam się Marie',
        options: ['Jestem Marie', 'Nazywam się Marie', 'Mam na imię Marie', 'Moje imię Marie'],
        explanation: '"Nazywam się" et "Mam na imię" s\'utilisent tous les deux. Le premier est légèrement plus formel.',
        xpReward: 10,
      },
      {
        id: 'ex_2_3_2',
        type: 'translation_fr_pl',
        question: 'Traduisez : "Enchanté(e)"',
        correctAnswer: 'Miło mi',
        options: ['Dziękuję', 'Przepraszam', 'Miło mi', 'Dobrze'],
        explanation: '"Miło mi" = Enchanté(e). Littéralement : "c\'est agréable pour moi".',
        xpReward: 10,
      },
      {
        id: 'ex_2_3_3',
        type: 'word_order',
        question: 'Formez : "Comment vous appelez-vous ?"',
        correctAnswer: 'Jak się pan nazywa',
        words: ['Jak', 'się', 'pan', 'nazywa'],
        explanation: '"Jak się pan/pani nazywa ?" = Comment vous appelez-vous ? (formel M/F)',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_2_4',
    moduleId: 'module_2',
    title: 'Oui, non, peut-être',
    description: 'Les réponses de base et les expressions d\'accord.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 4,
    xpReward: 50,
    estimatedMinutes: 3,
    isPremium: false,
    tags: ['bases', 'réponses'],
    exercises: [
      {
        id: 'ex_2_4_1',
        type: 'matching',
        question: 'Associez chaque expression à sa traduction',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Tak', right: 'Oui' },
          { left: 'Nie', right: 'Non' },
          { left: 'Może', right: 'Peut-être' },
          { left: 'Dobrze', right: 'D\'accord / Bien' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_2_4_2',
        type: 'multiple_choice',
        question: 'On vous propose quelque chose et vous acceptez. Vous dites :',
        correctAnswer: 'Tak, dziękuję',
        options: ['Nie, dziękuję', 'Tak, dziękuję', 'Może, proszę', 'Przepraszam'],
        explanation: '"Tak, dziękuję" = Oui, merci. "Nie, dziękuję" = Non, merci.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================
// src/content/lessons/module3.ts
// Module 3 — Chiffres et nombres (3 leçons)
// ============================================================

export const MODULE_3_LESSONS: Lesson[] = [
  {
    id: 'lesson_3_1',
    moduleId: 'module_3',
    title: 'Les chiffres de 1 à 10',
    description: 'Apprenez les chiffres fondamentaux du polonais.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 4,
    isPremium: false,
    tags: ['chiffres', 'bases'],
    exercises: [
      {
        id: 'ex_3_1_1',
        type: 'matching',
        question: 'Associez chaque chiffre à son nom polonais',
        correctAnswer: 'correct',
        pairs: [
          { left: '1', right: 'jeden' },
          { left: '2', right: 'dwa' },
          { left: '3', right: 'trzy' },
          { left: '4', right: 'cztery' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_3_1_2',
        type: 'multiple_choice',
        question: 'Comment dit-on "cinq" en polonais ?',
        correctAnswer: 'pięć',
        options: ['cztery', 'pięć', 'sześć', 'siedem'],
        explanation: 'pięć = 5. La notation "ę" donne un son nasal.',
        xpReward: 10,
      },
      {
        id: 'ex_3_1_3',
        type: 'word_order',
        question: 'Mettez dans l\'ordre croissant : "trzy, jeden, dwa"',
        correctAnswer: 'jeden dwa trzy',
        words: ['trzy', 'jeden', 'dwa'],
        explanation: 'jedan (1) → dwa (2) → trzy (3)',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_3_2',
    moduleId: 'module_3',
    title: 'De 10 à 100',
    description: 'Les dizaines et comment former les nombres composés.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 2,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['chiffres', 'dizaines'],
    exercises: [
      {
        id: 'ex_3_2_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "vingt" ?',
        correctAnswer: 'dwadzieścia',
        options: ['dziesięć', 'dwadzieścia', 'trzydzieści', 'czterdzieści'],
        explanation: 'dwadzieścia = 20. La terminaison "-dzieścia" indique les dizaines de 20 à 40.',
        xpReward: 10,
      },
      {
        id: 'ex_3_2_2',
        type: 'translation_fr_pl',
        question: 'Comment dit-on "cent" ?',
        correctAnswer: 'sto',
        options: ['sto', 'tysiąc', 'pięćdziesiąt', 'dziewięćdziesiąt'],
        explanation: 'sto = 100. "Sto lat !" est la chanson d\'anniversaire polonaise.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_3_3',
    moduleId: 'module_3',
    title: 'Quel âge avez-vous ?',
    description: 'Utiliser les chiffres pour parler de l\'âge.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 3,
    xpReward: 50,
    estimatedMinutes: 4,
    isPremium: false,
    tags: ['chiffres', 'âge', 'conversation'],
    exercises: [
      {
        id: 'ex_3_3_1',
        type: 'multiple_choice',
        question: 'Comment demande-t-on l\'âge de façon informelle ?',
        correctAnswer: 'Ile masz lat?',
        options: ['Jak się masz?', 'Ile masz lat?', 'Skąd jesteś?', 'Co robisz?'],
        explanation: '"Ile masz lat ?" = Quel âge as-tu ? "Ile" = combien, "lat" = ans.',
        xpReward: 10,
      },
      {
        id: 'ex_3_3_2',
        type: 'fill_blank',
        question: 'Répondez : "J\'ai trente ans" → "Mam ___ lat"',
        correctAnswer: 'trzydzieści',
        options: ['dwadzieścia', 'trzydzieści', 'czterdzieści', 'pięćdziesiąt'],
        explanation: '"Mam trzydzieści lat" = J\'ai trente ans. "Mam" = j\'ai.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
