// ============================================================
// src/content/lessons/module2.ts
// Module 2 — Salutations essentielles (4 leçons)
// ============================================================

import type { Lesson } from '@/types';
import { CONTACT_VOCAB } from '@/content/vocabulary/module2';

export const MODULE_2_LESSONS: Lesson[] = [
  {
    id: 'lesson_2_1',
    moduleId: 'module_2',
    title: 'Dire bonjour et au revoir',
    description: 'Les formules de salutation formelles et informelles.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 3,
    isPremium: false,
    tags: ['salutations', 'bases', 'premier_contact'],
    discoveryItems: CONTACT_VOCAB,
    exercises: [
      {
        id: 'ex_2_1_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "salut" de façon informelle ?',
        correctAnswer: 'cześć',
        options: ['cześć', 'dzień dobry', 'dobranoc', 'pa'],
        explanation: 'cześć = salut / coucou (informel).',
        xpReward: 10,
      },
      {
        id: 'ex_2_1_2',
        type: 'matching',
        question: 'Associez chaque formule à sa traduction',
        correctAnswer: 'correct',
        pairs: [
          { left: '👋', right: 'cześć' },
          { left: '☀️', right: 'dzień dobry' },
          { left: '🌙', right: 'dobranoc' },
          { left: '🖐️', right: 'pa' },
        ],
        xpReward: 15,
      },
      {
        id: 'ex_2_1_3',
        type: 'word_order',
        question: 'Écoutez et reconstituez la phrase :',
        correctAnswer: 'Cześć! Jak się masz?',
        words: ['Cześć!', 'Jak', 'się', 'masz?'],
        isAudioPrompt: true,
        audioText: 'Cześć! Jak się masz?',
        xpReward: 15,
      },
      {
        id: 'ex_2_1_4',
        type: 'multiple_choice',
        question: 'Quelle expression utiliser avec un inconnu pour dire bonjour ?',
        correctAnswer: 'dzień dobry',
        options: ['dzień dobry', 'cześć', 'pa', 'dobranoc'],
        explanation: 'Dans un cadre formel ou avec un inconnu, utilisez "dzień dobry".',
        xpReward: 10,
      },
      {
        id: 'ex_2_1_5',
        type: 'matching',
        question: 'Associez chaque expression à sa traduction',
        correctAnswer: 'correct',
        pairs: [
          { left: 'dobry wieczór', right: 'bonsoir' },
          { left: 'do widzenia', right: 'au revoir (formel)' },
          { left: 'pa', right: 'au revoir (informel)' },
        ],
        xpReward: 15,
      },
      {
        id: 'ex_2_1_6',
        type: 'word_order',
        question: 'Reconstituez la phrase : "Au revoir ! Bonne journée !"',
        correctAnswer: 'Do widzenia! Miłego dnia!',
        words: ['Do', 'widzenia!', 'Miłego', 'dnia!'],
        xpReward: 15,
      },
      {
        id: 'ex_2_1_7',
        type: 'fill_blank',
        question: 'Complétez : "Idę spać... ___!" (Je vais dormir... bonne nuit !)',
        correctAnswer: 'dobranoc',
        options: ['dobranoc', 'dzień dobry', 'cześć', 'dobry wieczór'],
        explanation: 'dobranoc = bonne nuit.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_2_2',
    moduleId: 'module_2',
    title: 'Merci, pardon, s\'il vous plaît',
    description: 'Les formules de politesse indispensables au quotidien.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 2,
    xpReward: 50,
    estimatedMinutes: 4,
    isPremium: false,
    tags: ['politesse', 'bases'],
    exercises: [
      {
        id: 'ex_2_2_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "Excusez-moi" pour attirer l\'attention ?',
        correctAnswer: 'Przepraszam',
        options: ['Dziękuję', 'Przepraszam', 'Proszę', 'Dobrze'],
        explanation: '"Przepraszam" est polyvalent : pardon, excusez-moi, je suis désolé.',
        xpReward: 10,
      },
      {
        id: 'ex_2_2_2',
        type: 'translation_pl_fr',
        question: 'Que signifie "Proszę bardzo" ?',
        correctAnswer: 'Je vous en prie / Voici',
        options: ['S\'il vous plaît', 'Je vous en prie / Voici', 'Merci beaucoup', 'De rien'],
        explanation: '"Proszę" = s\'il vous plaît / voici. "Proszę bardzo" = je vous en prie / voici.',
        xpReward: 10,
      },
      {
        id: 'ex_2_2_3',
        type: 'fill_blank',
        question: 'Complétez : "___ za pomoc !" (Merci pour l\'aide !)',
        correctAnswer: 'Dziękuję',
        options: ['Przepraszam', 'Dziękuję', 'Proszę', 'Dobrze'],
        explanation: '"Dziękuję za..." = Merci pour... C\'est la structure de base.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_2_3',
    moduleId: 'module_2',
    title: 'Se présenter',
    description: 'Dire son prénom, demander comment s\'appelle quelqu\'un.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 3,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['présentations', 'identité'],
    exercises: [
      {
        id: 'ex_2_3_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "Je m\'appelle Marie" en polonais ?',
        correctAnswer: 'Nazywam się Marie',
        options: ['Jestem Marie', 'Nazywam się Marie', 'Mam na imię Marie', 'Moje imię Marie'],
        explanation: '"Nazywam się" et "Mam na imię" s\'utilisent tous les deux. Le premier est légèrement plus formel.',
        xpReward: 10,
      },
      {
        id: 'ex_2_3_2',
        type: 'translation_fr_pl',
        question: 'Traduisez : "Enchanté(e)"',
        correctAnswer: 'Miło mi',
        options: ['Dziękuję', 'Przepraszam', 'Miło mi', 'Dobrze'],
        explanation: '"Miło mi" = Enchanté(e). Littéralement : "c\'est agréable pour moi".',
        xpReward: 10,
      },
      {
        id: 'ex_2_3_3',
        type: 'word_order',
        question: 'Formez : "Comment vous appelez-vous ?"',
        correctAnswer: 'Jak się pan nazywa',
        words: ['Jak', 'się', 'pan', 'nazywa'],
        explanation: '"Jak się pan/pani nazywa ?" = Comment vous appelez-vous ? (formel M/F)',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_2_4',
    moduleId: 'module_2',
    title: 'Oui, non, peut-être',
    description: 'Les réponses de base et les expressions d\'accord.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 4,
    xpReward: 50,
    estimatedMinutes: 3,
    isPremium: false,
    tags: ['bases', 'réponses'],
    exercises: [
      {
        id: 'ex_2_4_1',
        type: 'matching',
        question: 'Associez chaque expression à sa traduction',
        correctAnswer: 'correct',
        pairs: [
          { left: 'Tak', right: 'Oui' },
          { left: 'Nie', right: 'Non' },
          { left: 'Może', right: 'Peut-être' },
          { left: 'Dobrze', right: 'D\'accord / Bien' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_2_4_2',
        type: 'multiple_choice',
        question: 'On vous propose quelque chose et vous acceptez. Vous dites :',
        correctAnswer: 'Tak, dziękuję',
        options: ['Nie, dziękuję', 'Tak, dziękuję', 'Może, proszę', 'Przepraszam'],
        explanation: '"Tak, dziękuję" = Oui, merci. "Nie, dziękuję" = Non, merci.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================
// src/content/lessons/module3.ts
// Module 3 — Chiffres et nombres (3 leçons)
// ============================================================

export const MODULE_3_LESSONS: Lesson[] = [
  {
    id: 'lesson_3_1',
    moduleId: 'module_3',
    title: 'Les chiffres de 1 à 10',
    description: 'Apprenez les chiffres fondamentaux du polonais.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 1,
    xpReward: 50,
    estimatedMinutes: 4,
    isPremium: false,
    tags: ['chiffres', 'bases'],
    exercises: [
      {
        id: 'ex_3_1_1',
        type: 'matching',
        question: 'Associez chaque chiffre à son nom polonais',
        correctAnswer: 'correct',
        pairs: [
          { left: '1', right: 'jeden' },
          { left: '2', right: 'dwa' },
          { left: '3', right: 'trzy' },
          { left: '4', right: 'cztery' },
        ],
        xpReward: 20,
      },
      {
        id: 'ex_3_1_2',
        type: 'multiple_choice',
        question: 'Comment dit-on "cinq" en polonais ?',
        correctAnswer: 'pięć',
        options: ['cztery', 'pięć', 'sześć', 'siedem'],
        explanation: 'pięć = 5. La notation "ę" donne un son nasal.',
        xpReward: 10,
      },
      {
        id: 'ex_3_1_3',
        type: 'word_order',
        question: 'Mettez dans l\'ordre croissant : "trzy, jeden, dwa"',
        correctAnswer: 'jeden dwa trzy',
        words: ['trzy', 'jeden', 'dwa'],
        explanation: 'jedan (1) → dwa (2) → trzy (3)',
        xpReward: 15,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_3_2',
    moduleId: 'module_3',
    title: 'De 10 à 100',
    description: 'Les dizaines et comment former les nombres composés.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 2,
    xpReward: 50,
    estimatedMinutes: 5,
    isPremium: false,
    tags: ['chiffres', 'dizaines'],
    exercises: [
      {
        id: 'ex_3_2_1',
        type: 'multiple_choice',
        question: 'Comment dit-on "vingt" ?',
        correctAnswer: 'dwadzieścia',
        options: ['dziesięć', 'dwadzieścia', 'trzydzieści', 'czterdzieści'],
        explanation: 'dwadzieścia = 20. La terminaison "-dzieścia" indique les dizaines de 20 à 40.',
        xpReward: 10,
      },
      {
        id: 'ex_3_2_2',
        type: 'translation_fr_pl',
        question: 'Comment dit-on "cent" ?',
        correctAnswer: 'sto',
        options: ['sto', 'tysiąc', 'pięćdziesiąt', 'dziewięćdziesiąt'],
        explanation: 'sto = 100. "Sto lat !" est la chanson d\'anniversaire polonaise.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lesson_3_3',
    moduleId: 'module_3',
    title: 'Quel âge avez-vous ?',
    description: 'Utiliser les chiffres pour parler de l\'âge.',
    type: 'vocabulary',
    difficulty: 'A1',
    order: 3,
    xpReward: 50,
    estimatedMinutes: 4,
    isPremium: false,
    tags: ['chiffres', 'âge', 'conversation'],
    exercises: [
      {
        id: 'ex_3_3_1',
        type: 'multiple_choice',
        question: 'Comment demande-t-on l\'âge de façon informelle ?',
        correctAnswer: 'Ile masz lat?',
        options: ['Jak się masz?', 'Ile masz lat?', 'Skąd jesteś?', 'Co robisz?'],
        explanation: '"Ile masz lat ?" = Quel âge as-tu ? "Ile" = combien, "lat" = ans.',
        xpReward: 10,
      },
      {
        id: 'ex_3_3_2',
        type: 'fill_blank',
        question: 'Répondez : "J\'ai trente ans" → "Mam ___ lat"',
        correctAnswer: 'trzydzieści',
        options: ['dwadzieścia', 'trzydzieści', 'czterdzieści', 'pięćdziesiąt'],
        explanation: '"Mam trzydzieści lat" = J\'ai trente ans. "Mam" = j\'ai.',
        xpReward: 10,
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
