// ============================================================
// src/content/flashcards/flashcards.ts
// 50 flashcards initiales — 5 thèmes × 10 mots
// ============================================================

import type { Flashcard } from '@/types';

export const FLASHCARDS: Flashcard[] = [

  // ── THÈME 1 : SALUTATIONS (10 mots) ────────────────────────
  {
    id: 'fc_sal_01', moduleId: 'module_2', isPremium: false,
    front: 'Dzień dobry', back: 'Bonjour (formel)',
    phonetic: '[dʑɛɲ ˈdɔbrɨ]',
    examplePl: 'Dzień dobry, jak się pan miewa?',
    exampleFr: 'Bonjour, comment allez-vous ?',
    tags: ['salutations', 'formel'],
  },
  {
    id: 'fc_sal_02', moduleId: 'module_2', isPremium: false,
    front: 'Cześć', back: 'Salut (informel)',
    phonetic: '[tʂɛɕtɕ]',
    examplePl: 'Cześć, co słychać?',
    exampleFr: 'Salut, quoi de neuf ?',
    tags: ['salutations', 'informel'],
  },
  {
    id: 'fc_sal_03', moduleId: 'module_2', isPremium: false,
    front: 'Do widzenia', back: 'Au revoir',
    phonetic: '[dɔ viˈdzɛɲa]',
    examplePl: 'Do widzenia, do jutra!',
    exampleFr: 'Au revoir, à demain !',
    tags: ['salutations', 'adieux'],
  },
  {
    id: 'fc_sal_04', moduleId: 'module_2', isPremium: false,
    front: 'Dziękuję', back: 'Merci',
    phonetic: '[dʑɛŋˈkujɛ]',
    examplePl: 'Dziękuję bardzo za pomoc.',
    exampleFr: 'Merci beaucoup pour l\'aide.',
    tags: ['politesse'],
  },
  {
    id: 'fc_sal_05', moduleId: 'module_2', isPremium: false,
    front: 'Przepraszam', back: 'Pardon / Excusez-moi',
    phonetic: '[pʂɛˈpraʂam]',
    examplePl: 'Przepraszam, gdzie jest toaleta?',
    exampleFr: 'Excusez-moi, où sont les toilettes ?',
    tags: ['politesse', 'essentiel'],
  },
  {
    id: 'fc_sal_06', moduleId: 'module_2', isPremium: false,
    front: 'Proszę', back: 'S\'il vous plaît / Voici',
    phonetic: '[ˈprɔʂɛ]',
    examplePl: 'Proszę, to dla pana.',
    exampleFr: 'Voici, c\'est pour vous.',
    tags: ['politesse'],
  },
  {
    id: 'fc_sal_07', moduleId: 'module_2', isPremium: false,
    front: 'Dobranoc', back: 'Bonne nuit',
    phonetic: '[dɔˈbranɔts]',
    examplePl: 'Dobranoc, śpij dobrze!',
    exampleFr: 'Bonne nuit, dors bien !',
    tags: ['salutations', 'adieux'],
  },
  {
    id: 'fc_sal_08', moduleId: 'module_2', isPremium: false,
    front: 'Jak się masz?', back: 'Comment vas-tu ?',
    phonetic: '[jak ɕɛ maʂ]',
    examplePl: 'Cześć! Jak się masz?',
    exampleFr: 'Salut ! Comment vas-tu ?',
    tags: ['salutations', 'informel'],
  },
  {
    id: 'fc_sal_09', moduleId: 'module_2', isPremium: false,
    front: 'Dobrze', back: 'Bien / D\'accord',
    phonetic: '[ˈdɔbʐɛ]',
    examplePl: 'Dobrze, rozumiem.',
    exampleFr: 'Bien, je comprends.',
    tags: ['expressions'],
  },
  {
    id: 'fc_sal_10', moduleId: 'module_2', isPremium: false,
    front: 'Miło mi', back: 'Enchanté(e)',
    phonetic: '[ˈmiwɔ mi]',
    examplePl: 'Miło mi pana poznać.',
    exampleFr: 'Enchanté de faire votre connaissance.',
    tags: ['salutations', 'présentations'],
  },

  // ── THÈME 2 : CHIFFRES (10 mots) ────────────────────────────
  {
    id: 'fc_num_01', moduleId: 'module_3', isPremium: false,
    front: 'jeden', back: 'un (1)',
    phonetic: '[ˈjɛdɛn]',
    examplePl: 'Mam jeden bilet.',
    exampleFr: 'J\'ai un billet.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_02', moduleId: 'module_3', isPremium: false,
    front: 'dwa', back: 'deux (2)',
    phonetic: '[dva]',
    examplePl: 'Proszę dwa bilety.',
    exampleFr: 'Deux billets, s\'il vous plaît.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_03', moduleId: 'module_3', isPremium: false,
    front: 'trzy', back: 'trois (3)',
    phonetic: '[tʂɨ]',
    examplePl: 'Mam trzy dzieci.',
    exampleFr: 'J\'ai trois enfants.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_04', moduleId: 'module_3', isPremium: false,
    front: 'cztery', back: 'quatre (4)',
    phonetic: '[ˈtʂtɛrɨ]',
    examplePl: 'Cztery pory roku.',
    exampleFr: 'Les quatre saisons.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_05', moduleId: 'module_3', isPremium: false,
    front: 'pięć', back: 'cinq (5)',
    phonetic: '[pjɛɲtɕ]',
    examplePl: 'Pięć minut, proszę.',
    exampleFr: 'Cinq minutes, s\'il vous plaît.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_06', moduleId: 'module_3', isPremium: false,
    front: 'dziesięć', back: 'dix (10)',
    phonetic: '[ˈdʑɛɕɛɲtɕ]',
    examplePl: 'Mam dziesięć euro.',
    exampleFr: 'J\'ai dix euros.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_07', moduleId: 'module_3', isPremium: false,
    front: 'dwadzieścia', back: 'vingt (20)',
    phonetic: '[dvaˈdʑɛɕtɕa]',
    examplePl: 'Dwadzieścia złotych.',
    exampleFr: 'Vingt zlotys.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_08', moduleId: 'module_3', isPremium: false,
    front: 'sto', back: 'cent (100)',
    phonetic: '[stɔ]',
    examplePl: 'Sto lat! (Joyeux anniversaire)',
    exampleFr: 'Cent ans ! (formule de vœux)',
    tags: ['chiffres', 'culture'],
  },
  {
    id: 'fc_num_09', moduleId: 'module_3', isPremium: false,
    front: 'tysiąc', back: 'mille (1 000)',
    phonetic: '[ˈtɨɕɔɲts]',
    examplePl: 'Tysiąc złotych.',
    exampleFr: 'Mille zlotys.',
    tags: ['chiffres'],
  },
  {
    id: 'fc_num_10', moduleId: 'module_3', isPremium: false,
    front: 'zero', back: 'zéro (0)',
    phonetic: '[ˈzɛrɔ]',
    examplePl: 'Zero problemów!',
    exampleFr: 'Zéro problème !',
    tags: ['chiffres'],
  },

  // ── THÈME 3 : FAMILLE (10 mots) ─────────────────────────────
  {
    id: 'fc_fam_01', moduleId: 'module_4', isPremium: false,
    front: 'mama', back: 'maman',
    phonetic: '[ˈmama]',
    examplePl: 'Moja mama jest lekarzem.',
    exampleFr: 'Ma maman est médecin.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_02', moduleId: 'module_4', isPremium: false,
    front: 'tata / ojciec', back: 'papa / père',
    phonetic: '[ˈtata] / [ˈɔjtsɛts]',
    examplePl: 'Mój tata pracuje w Krakowie.',
    exampleFr: 'Mon papa travaille à Cracovie.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_03', moduleId: 'module_4', isPremium: false,
    front: 'brat', back: 'frère',
    phonetic: '[brat]',
    examplePl: 'Mam dwóch braci.',
    exampleFr: 'J\'ai deux frères.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_04', moduleId: 'module_4', isPremium: false,
    front: 'siostra', back: 'sœur',
    phonetic: '[ˈɕɔstra]',
    examplePl: 'Moja siostra mieszka w Warszawie.',
    exampleFr: 'Ma sœur habite à Varsovie.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_05', moduleId: 'module_4', isPremium: false,
    front: 'dziadek', back: 'grand-père',
    phonetic: '[ˈdʑadɛk]',
    examplePl: 'Dziadek ma osiemdziesiąt lat.',
    exampleFr: 'Grand-père a quatre-vingts ans.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_06', moduleId: 'module_4', isPremium: false,
    front: 'babcia', back: 'grand-mère',
    phonetic: '[ˈbabtɕa]',
    examplePl: 'Babcia robi pyszne pierogi.',
    exampleFr: 'Grand-mère fait de délicieux pierogis.',
    tags: ['famille', 'cuisine'],
  },
  {
    id: 'fc_fam_07', moduleId: 'module_4', isPremium: false,
    front: 'syn', back: 'fils',
    phonetic: '[sɨn]',
    examplePl: 'Mój syn ma pięć lat.',
    exampleFr: 'Mon fils a cinq ans.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_08', moduleId: 'module_4', isPremium: false,
    front: 'córka', back: 'fille',
    phonetic: '[ˈtsurka]',
    examplePl: 'Moja córka chodzi do szkoły.',
    exampleFr: 'Ma fille va à l\'école.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_09', moduleId: 'module_4', isPremium: false,
    front: 'mąż', back: 'mari',
    phonetic: '[mɔ̃ʂ]',
    examplePl: 'Mój mąż jest Polakiem.',
    exampleFr: 'Mon mari est polonais.',
    tags: ['famille'],
  },
  {
    id: 'fc_fam_10', moduleId: 'module_4', isPremium: false,
    front: 'żona', back: 'femme / épouse',
    phonetic: '[ˈʐɔna]',
    examplePl: 'Moja żona mówi po francusku.',
    exampleFr: 'Ma femme parle français.',
    tags: ['famille'],
  },

  // ── THÈME 4 : NOURRITURE (10 mots) ──────────────────────────
  {
    id: 'fc_food_01', moduleId: 'module_5', isPremium: false,
    front: 'pierogi', back: 'raviolis polonais',
    phonetic: '[pjɛˈrɔɡʲi]',
    examplePl: 'Pierogi z kapustą są pyszne.',
    exampleFr: 'Les pierogis à la choucroute sont délicieux.',
    tags: ['nourriture', 'culture'],
  },
  {
    id: 'fc_food_02', moduleId: 'module_5', isPremium: false,
    front: 'bigos', back: 'ragoût de choucroute',
    phonetic: '[ˈbiɡɔs]',
    examplePl: 'Bigos to tradycyjne polskie danie.',
    exampleFr: 'Le bigos est un plat traditionnel polonais.',
    tags: ['nourriture', 'culture'],
  },
  {
    id: 'fc_food_03', moduleId: 'module_5', isPremium: false,
    front: 'chleb', back: 'pain',
    phonetic: '[xlɛp]',
    examplePl: 'Proszę dwa chleby.',
    exampleFr: 'Deux pains, s\'il vous plaît.',
    tags: ['nourriture', 'boulangerie'],
  },
  {
    id: 'fc_food_04', moduleId: 'module_5', isPremium: false,
    front: 'woda', back: 'eau',
    phonetic: '[ˈvɔda]',
    examplePl: 'Poproszę wodę mineralną.',
    exampleFr: 'Je voudrais de l\'eau minérale.',
    tags: ['boissons', 'restaurant'],
  },
  {
    id: 'fc_food_05', moduleId: 'module_5', isPremium: false,
    front: 'piwo', back: 'bière',
    phonetic: '[ˈpivɔ]',
    examplePl: 'Jedno piwo, proszę.',
    exampleFr: 'Une bière, s\'il vous plaît.',
    tags: ['boissons', 'bar'],
  },
  {
    id: 'fc_food_06', moduleId: 'module_5', isPremium: false,
    front: 'kawa', back: 'café',
    phonetic: '[ˈkava]',
    examplePl: 'Kawa z mlekiem, proszę.',
    exampleFr: 'Un café au lait, s\'il vous plaît.',
    tags: ['boissons'],
  },
  {
    id: 'fc_food_07', moduleId: 'module_5', isPremium: false,
    front: 'zupa', back: 'soupe',
    phonetic: '[ˈzupa]',
    examplePl: 'Zupa pomidorowa jest gotowa.',
    exampleFr: 'La soupe aux tomates est prête.',
    tags: ['nourriture', 'restaurant'],
  },
  {
    id: 'fc_food_08', moduleId: 'module_5', isPremium: false,
    front: 'mięso', back: 'viande',
    phonetic: '[ˈmjɛnsɔ]',
    examplePl: 'Nie jem mięsa.',
    exampleFr: 'Je ne mange pas de viande.',
    tags: ['nourriture', 'restaurant'],
  },
  {
    id: 'fc_food_09', moduleId: 'module_5', isPremium: false,
    front: 'ryba', back: 'poisson',
    phonetic: '[ˈrɨba]',
    examplePl: 'Ryba jest świeża.',
    exampleFr: 'Le poisson est frais.',
    tags: ['nourriture'],
  },
  {
    id: 'fc_food_10', moduleId: 'module_5', isPremium: false,
    front: 'rachunek', back: 'l\'addition',
    phonetic: '[raˈxunɛk]',
    examplePl: 'Poproszę rachunek.',
    exampleFr: 'L\'addition, s\'il vous plaît.',
    tags: ['restaurant', 'essentiel'],
  },

  // ── THÈME 5 : VOYAGE & TRANSPORT (10 mots) ──────────────────
  {
    id: 'fc_tra_01', moduleId: 'module_6', isPremium: false,
    front: 'dworzec', back: 'gare',
    phonetic: '[ˈdvɔʐɛts]',
    examplePl: 'Gdzie jest dworzec PKP?',
    exampleFr: 'Où est la gare ?',
    tags: ['voyage', 'transport'],
  },
  {
    id: 'fc_tra_02', moduleId: 'module_6', isPremium: false,
    front: 'pociąg', back: 'train',
    phonetic: '[ˈpɔtɕɔŋk]',
    examplePl: 'Pociąg do Krakowa odjeżdża o 10:00.',
    exampleFr: 'Le train pour Cracovie part à 10h.',
    tags: ['voyage', 'transport'],
  },
  {
    id: 'fc_tra_03', moduleId: 'module_6', isPremium: false,
    front: 'lotnisko', back: 'aéroport',
    phonetic: '[lɔtˈɲiskɔ]',
    examplePl: 'Jak dojechać na lotnisko?',
    exampleFr: 'Comment aller à l\'aéroport ?',
    tags: ['voyage'],
  },
  {
    id: 'fc_tra_04', moduleId: 'module_6', isPremium: false,
    front: 'bilet', back: 'billet / ticket',
    phonetic: '[ˈbilɛt]',
    examplePl: 'Proszę dwa bilety w obie strony.',
    exampleFr: 'Deux billets aller-retour, s\'il vous plaît.',
    tags: ['voyage', 'transport'],
  },
  {
    id: 'fc_tra_05', moduleId: 'module_6', isPremium: false,
    front: 'hotel', back: 'hôtel',
    phonetic: '[ˈxɔtɛl]',
    examplePl: 'Szukam hotelu w centrum.',
    exampleFr: 'Je cherche un hôtel au centre-ville.',
    tags: ['voyage', 'hébergement'],
  },
  {
    id: 'fc_tra_06', moduleId: 'module_6', isPremium: false,
    front: 'ulica', back: 'rue',
    phonetic: '[ˈulitsa]',
    examplePl: 'Na której ulicy mieszkasz?',
    exampleFr: 'Dans quelle rue habites-tu ?',
    tags: ['ville'],
  },
  {
    id: 'fc_tra_07', moduleId: 'module_6', isPremium: false,
    front: 'apteka', back: 'pharmacie',
    phonetic: '[apˈtɛka]',
    examplePl: 'Gdzie jest najbliższa apteka?',
    exampleFr: 'Où est la pharmacie la plus proche ?',
    tags: ['ville', 'santé'],
  },
  {
    id: 'fc_tra_08', moduleId: 'module_6', isPremium: false,
    front: 'sklep', back: 'magasin',
    phonetic: '[sklɛp]',
    examplePl: 'Sklep jest otwarty do 20:00.',
    exampleFr: 'Le magasin est ouvert jusqu\'à 20h.',
    tags: ['ville', 'shopping'],
  },
  {
    id: 'fc_tra_09', moduleId: 'module_6', isPremium: false,
    front: 'prawo / lewo', back: 'à droite / à gauche',
    phonetic: '[ˈpravɔ] / [ˈlɛvɔ]',
    examplePl: 'Proszę skręcić w prawo.',
    exampleFr: 'Tournez à droite, s\'il vous plaît.',
    tags: ['direction', 'essentiel'],
  },
  {
    id: 'fc_tra_10', moduleId: 'module_6', isPremium: false,
    front: 'pomoc!', back: 'Au secours !',
    phonetic: '[ˈpɔmɔts]',
    examplePl: 'Pomocy! Potrzebuję lekarza!',
    exampleFr: 'Au secours ! J\'ai besoin d\'un médecin !',
    tags: ['urgence', 'essentiel'],
  },
];
